# Generated by Django 5.0.3 on 2024-03-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
