# Generated by Django 5.0.3 on 2024-04-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobank', '0002_photo_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='deleted',
            new_name='hidden',
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INP', 'In Progress'), ('RED', 'Ready')], default='NEW', max_length=3),
        ),
    ]
