# Generated by Django 5.0.3 on 2024-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobank', '0003_alter_photo_options_rename_deleted_photo_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='superresolution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WPR', 'Wait Processing'), ('INP', 'In Progress'), ('RED', 'Ready')], default='NEW', max_length=3),
        ),
    ]
