# Generated by Django 5.0.3 on 2024-04-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobank', '0004_photo_superresolution_alter_photo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='daytime',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='extension',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_duplicate',
            field=models.BooleanField(default=False, verbose_name='Дубликат'),
        ),
        migrations.AddField(
            model_name='photo',
            name='orientation',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='season',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='superresolution',
            field=models.BooleanField(default=False, verbose_name='Improve quality'),
        ),
    ]
