# Generated by Django 5.0.3 on 2024-04-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobank', '0005_photo_daytime_photo_extension_photo_is_duplicate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WPR', 'Wait Processing'), ('INP', 'In Progress'), ('RED', 'Ready'), ('FAL', 'Fail')], default='NEW', max_length=3),
        ),
    ]
