/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NavImport } from './routes/_nav'
import { Route as NavEventsImport } from './routes/_nav/_events'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const NavIndexLazyImport = createFileRoute('/_nav/')()
const NavEventsEventsIndexLazyImport = createFileRoute(
  '/_nav/_events/events/',
)()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const NavRoute = NavImport.update({
  id: '/_nav',
  getParentRoute: () => rootRoute,
} as any)

const NavIndexLazyRoute = NavIndexLazyImport.update({
  path: '/',
  getParentRoute: () => NavRoute,
} as any).lazy(() => import('./routes/_nav/index.lazy').then((d) => d.Route))

const NavEventsRoute = NavEventsImport.update({
  id: '/_events',
  getParentRoute: () => NavRoute,
} as any)

const NavEventsEventsIndexLazyRoute = NavEventsEventsIndexLazyImport.update({
  path: '/events/',
  getParentRoute: () => NavEventsRoute,
} as any).lazy(() =>
  import('./routes/_nav/_events/events/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_nav': {
      preLoaderRoute: typeof NavImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/_nav/_events': {
      preLoaderRoute: typeof NavEventsImport
      parentRoute: typeof NavImport
    }
    '/_nav/': {
      preLoaderRoute: typeof NavIndexLazyImport
      parentRoute: typeof NavImport
    }
    '/_nav/_events/events/': {
      preLoaderRoute: typeof NavEventsEventsIndexLazyImport
      parentRoute: typeof NavEventsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  NavRoute.addChildren([
    NavEventsRoute.addChildren([NavEventsEventsIndexLazyRoute]),
    NavIndexLazyRoute,
  ]),
  LoginLazyRoute,
])

/* prettier-ignore-end */
