/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NavImport } from './routes/_nav'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const NavIndexLazyImport = createFileRoute('/_nav/')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const NavRoute = NavImport.update({
  id: '/_nav',
  getParentRoute: () => rootRoute,
} as any)

const NavIndexLazyRoute = NavIndexLazyImport.update({
  path: '/',
  getParentRoute: () => NavRoute,
} as any).lazy(() => import('./routes/_nav/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_nav': {
      preLoaderRoute: typeof NavImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/_nav/': {
      preLoaderRoute: typeof NavIndexLazyImport
      parentRoute: typeof NavImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  NavRoute.addChildren([NavIndexLazyRoute]),
  LoginLazyRoute,
])

/* prettier-ignore-end */
